#!/bin/sh
#
# Start px3-se linux service/window....
#

case "$1" in
  start)
	px3seBase -i
	export MALLOC_CHECK_=0
	export LC_ALL='zh_CN.utf8'
	export QT_EGLFSPLATFORM_USE_GST_VIDEOSINK=1
	export QT_GSTREAMER_WINDOW_VIDEOSINK=kmssink
	/usr/local/QLauncher/QLauncher -platform EGLFS &
	/usr/bin/power_manager_service &
	/usr/bin/audioservice &
	;;
  stop)
        ;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
