IS_ANDROID_OS = false
IS_NEED_SHARED_PTR = false
IS_NEED_COMPILE_STLPORT = false
IS_NEED_LINK_STLPORT = false
IS_NEED_COMPILE_TINYXML2 = true
IS_NEED_COMPILE_EXPAT = true
IS_SUPPORT_ION = true
#IS_SUPPORT_DRM = true
IS_BUILD_TEST_APP = true
IS_CAM_IA10_API = false
IS_RK_ISP10 = false
IS_USE_RK_V4L2_HEAD = true
CROSS_COMPILE ?= $(CURDIR)/../../../../buildroot/output/host/usr/bin/arm-linux-
BASE_DIR ?= $(CURDIR)/../../../../buildroot/output/host/usr/arm-rockchip-linux-gnueabihf/sysroot
TARGET_DIR ?= $(BASE_DIR)/usr/lib
BUILD_OUPUT_EXTERNAL_LIBS:= $(TARGET_DIR)
#CROSS_COMPILE ?= /extra/zyc/android6.0/prebuilts/gcc/linux-x86/arm/arm-eabi-4.6/bin/arm-eabi-
#CROSS_COMPILE ?=
